caricamento esercizio regine.asp
unipr-org/PD pull request #7
Opened 2024-11-16 11:10 UTC by SimoneColli

caricamento esercizio relativo al posizionamento delle regine su una scacchiera

2024-11-16 11:18 UTC, merendamattia requested changes

2024-11-16 11:18 UTC, merendamattia commented on docker/examples/regine.asp
> +% Esampio: clingo -c n=4 regine.asp
typo

2024-11-16 11:18 UTC, merendamattia commented on docker/examples/regine.asp
> +
rimuovi le righe vuote multiple, lasciane al piu' una vuota

2024-11-16 12:09 UTC, merendamattia requested changes

2024-11-16 12:09 UTC, merendamattia commented on docker/examples/regine.asp
> +
anche qui devi togliere le righe vuote

2024-11-16 16:06 UTC, merendamattia approved these changes

2024-11-17 13:27 UTC, manueldiagostino approved these changes

2024-11-17 13:28 UTC, merged